version: "3.9"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DEFAULT_SYSTEM=postgres

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=codeshort
      - POSTGRES_PASSWORD=codeshort
      - POSTGRES_DB=codeshort
    volumes:
      - postgres-data:/var/lib/postgresql/data

  codeshort-backend:
    image: tannndev/codeshort-back:dev
    container_name: codeshort-backend
    build:
      context: ./codeshort-back
      dockerfile: /Dockerfile.local
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/codeshort
      - SPRING_DATASOURCE_USERNAME=codeshort
      - SPRING_DATASOURCE_PASSWORD=codeshort
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - codeshort-backend-resources:/codeshort-backend-resources
      
  codeshort-front:
    image: tannndev/codeshort-front:dev
    container_name: codeshort-front
    build:
      context: ./codeshort-front
      dockerfile: /Dockerfile.local
    restart: always
    ports:
      - 80:80
    depends_on:
      - codeshort-backend


volumes:
  codeshort-backend-resources:
  postgres-data: