version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # Mount Let's Encrypt certificates
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    depends_on:
      - codeshort-front
      - codeshort-backend
      - adminer

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      - ADMINER_DESIGN=pepa-linha

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    env_file: ".env"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  codeshort-backend:
    image: ghcr.io/tann-dev/codeshort-back:latest
    container_name: codeshort-backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    env_file: ".env"
    volumes:
      - codeshort-backend-resources:/codeshort-backend-resources

  codeshort-front:
    image: ghcr.io/tann-dev/codeshort-front:latest
    container_name: codeshort-front
    restart: always
    ports:
      - 4200:80
    depends_on:
      - codeshort-backend
    env_file: ".env"


volumes:
  codeshort-backend-resources:
  postgres-data: