version: "3.9"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DEFAULT_SYSTEM=postgres

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    env_file: ".env"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  codeshort-backend:
    image: ghcr.io/tann-dev/codeshort-backend:latest
    container_name: codeshort-backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    env_file: ".env"
    volumes:
      - codeshort-backend-resources:/codeshort-backend-resources
      
  codeshort-front:
    image: ghcr.io/tann-dev/codeshort-frontend:latest
    container_name: codeshort-front
    restart: always
    ports:
      - 4200:80
    depends_on:
      - codeshort-backend
    env_file: ".env"


volumes:
  codeshort-backend-resources:
  postgres-data: