version: "3.9"

services:
#   proxy:
#     image: nginxproxy/nginx-proxy
#     container_name: proxy
#     restart: always
#     ports:
#       - 80:80
#       - 443:443
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#       - /srv/docker/proxy/html:/usr/share/nginx/html
#       - ./vhosts:/etc/nginx/vhost.d
#       - /srv/docker/letsencrypt/certs:/etc/nginx/certs:ro

#   letsencrypt:
#     image: nginxproxy/acme-companion:2.0
#     container_name: letsencrypt
#     restart: always
#     depends_on:
#       - proxy
#     environment:
#       - DEFAULT_EMAIL=tann-dev@tann-dev.net
#     volumes_from:
#       - proxy
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - /srv/docker/letsencrypt/certs:/etc/nginx/certs
#       - /srv/docker/letsencrypt/acme.sh:/etc/acme.sh

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DEFAULT_SYSTEM=postgres

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=codeshort
      - POSTGRES_PASSWORD=codeshort
      - POSTGRES_DB=codeshort
    # Do not expose port publicly
    #    ports:
    #      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

################################################
  # Codeshort
  codeshort-backend:
    image: tannndev/codeshort-front:0.0.1
    container_name: codeshort-backend
    build: ./codeshort-back
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - postgres
    environment:
      # - VIRTUAL_HOST=codeshort.api.tann-dev.net
      # - VIRTUAL_PORT=8080
      # - LETSENCRYPT_HOST=codeshort.api.tann-dev.net
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/codeshort
      - SPRING_DATASOURCE_USERNAME=codeshort
      - SPRING_DATASOURCE_PASSWORD=codeshort
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      # - ./logs:/logs
      - codeshort-backend-resources:/codeshort-backend-resources
      
  codeshort-front:
    image: tannndev/codeshort-front:0.0.1
    container_name: codeshort-front
    build: ./codeshort-front
    restart: always
    ports:
      - 80:80
    depends_on:
      - codeshort-backend
    # environment:
    #   - VIRTUAL_HOST=codeshort.tann-dev.net
    #   - VIRTUAL_PORT=80
    #   - LETSENCRYPT_HOST=codeshort.tann-dev.net


volumes:
  codeshort-backend-resources:
  postgres-data: