version: '3.8'

services:

  db:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: codeshort # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: codeshort # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: codeshort # The PostgreSQL default database (automatically created at first launch)

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080