# Build stage
FROM maven:3.9.9-eclipse-temurin-21-alpine AS build
COPY . .
RUN mvn clean verify

# Package stage
FROM eclipse-temurin:21-alpine
COPY --from=build ./target/*.jar codeshort.jar
CMD ["java", "-jar", "codeshort.jar"]