apiVersion: v1
kind: Service
metadata:
  name: codeshort-front
spec:
  selector:
    app: codeshort-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort
