apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeshort-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codeshort-front
  template:
    metadata:
      labels:
        app: codeshort-front
        version: v1
    spec:
      containers:
        - name: codeshort-front
          image:  tannndev/codeshort-frontend:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80
