name: Publish prod image backend

on:
  push:
    branches:
      - master
    paths:
      - 'codeshort-back/**'
      - '.github/workflows/codeshort-back-workflow.yaml'
  pull_request:
    branches:
      - master
    paths:
      - 'codeshort-back/**'
      - '.github/workflows/codeshort-back-workflow.yaml'

jobs:
  build-back:

    name: Deploy Spring Boot App
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    #    server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
    #    settings-path: ${{ github.workspace }}/codeshort-back # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B verify --file codeshort-back/pom.xml

    #- name: Publish to GitHub Packages Apache Maven
    #  run: mvn deploy -s ${{ github.workspace }}/codeshort-back/settings.xml --file codeshort-back/pom.xml
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/tann-dev/codeshort-back:${{ secrets.MAJOR_BACK }}.${{ secrets.MINOR_BACK }}
        context: codeshort-back
    
    - name: Update Minor version
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'MINOR_BACK'
        value: $((${{ secrets.MINOR_BACK }}+1))
        token: ${{ secrets.SECRET_ACTION_ACCESS_TOKEN }}