name: Publish prod image

on:
  push:
    branches:
      - master
    paths:
      - 'codeshort-backend/src/**'
      - '.github/workflows/codeshort-backend-workflow.yaml'
  pull_request:
    branches:
      - master
    paths:
      - 'codeshort-backend/src/**'
      - '.github/workflows/codeshort-backend-workflow.yaml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file codeshort-back/pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
