name: Publish prod image frontend

on:
  push:
    branches:
      - master
    paths:
      - 'codeshort-front/**'
      - '.github/workflows/codeshort-frontend-workflow.yaml'
  pull_request:
    branches:
      - master
    paths:
      - 'codeshort-front/**'
      - '.github/workflows/codeshort-frontend-workflow.yaml'

jobs:
  build-frontend:
    
    name: Deploy Angular App
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18 LTS
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install NPM Modules
      working-directory: codeshort-front
      run: npm ci

    - name: Build Project
      working-directory: codeshort-front
      run: npm run buildDev

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/tann-dev/codeshort-frontend:${{ secrets.MAJOR_FRONT }}.${{ secrets.MINOR_FRONT }}
        context: codeshort-front

    - name: Update Minor version
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'MINOR_FRONT'
        value: $((${{ secrets.MINOR_FRONT }}+1))
        repository: EriksonGM/MasterReport
        token: ${{ secrets.REPO_ACCESS_TOKEN }}