name: Publish prod image backend

on:
  push:
    branches:
      - master
    paths:
      - 'codeshort-back/**'
      - '.github/workflows/codeshort-back-workflow.yaml'
  pull_request:
    branches:
      - master
    paths:
      - 'codeshort-back/**'
      - '.github/workflows/codeshort-back-workflow.yaml'

env:
  REGISTRY: ghcr.io # GitHub's registry

jobs:
  build-back:

    name: Deploy Spring Boot App
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Update minor version
      uses: action-pack/set-secret@v1
      with:
        name: 'MINOR_BACK'
        value: $((${{ secrets.MINOR_BACK }}+1))
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY}}/${{ github.repository }}-back
        tags: type=semver,pattern={{version}},value=1.${{ secrets.MAJOR_BACK }}.${{ secrets.MINOR_BACK }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B verify --file codeshort-back/pom.xml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY}}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: codeshort-back