name: Publish prod image backend

on:
  push:
    tags: [ v* ]

env:
  REGISTRY: ghcr.io # GitHub's registry

jobs:
  build-back:

    name: Deploy Spring Boot App
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    #    server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
    #    settings-path: ${{ github.workspace }}/codeshort-back # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B verify --file codeshort-back/pom.xml

    #- name: Publish to GitHub Packages Apache Maven
    #  run: mvn deploy -s ${{ github.workspace }}/codeshort-back/settings.xml --file codeshort-back/pom.xml
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY}}/${{ github.repository }}-back
        tags: type=semver,pattern={{version}},value=1.${{ secrets.MAJOR_BACK }}.${{ secrets.MINOR_BACK }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY}}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: codeshort-back
  
  build-front:
    
    name: Deploy Angular App
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18 LTS
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install NPM Modules
      working-directory: codeshort-front
      run: npm ci

    - name: Build Project
      working-directory: codeshort-front
      run: npm run build

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY}}/${{ github.repository }}-front
        tags: type=semver,pattern={{version}},value=1.${{ secrets.MAJOR_FRONT }}.${{ secrets.MINOR_FRONT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY}}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: codeshort-front