name: Publish prod image backend

on:
  push:
    tags: [ v* ]

env:
  REGISTRY: ghcr.io # GitHub's registry

jobs:
  build-back:

    name: Deploy Spring Boot App
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B verify --file codeshort-back/pom.xml

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY}}/${{ github.repository }}-back
        tags: ${{ steps.meta.outputs.tags }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY}}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: codeshort-back
  
  build-front:
    
    name: Deploy Angular App
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 22 LTS
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install NPM Modules
      working-directory: codeshort-front
      run: npm ci

    - name: Build Project
      working-directory: codeshort-front
      run: npm run build

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY}}/${{ github.repository }}-front
        tags: ${{ steps.meta.outputs.tags }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY}}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: codeshort-front